name: 'IPS Plugin Build'
description: 'Build an IPS plugin into a plugin XML'
author: 'LTT Forum'
inputs:
  name:
    description: 'The plugin name'
    required: true
  author:
    description: 'The plugin author'
    required: false
  website:
    description: 'The plugin website'
    required: false
  path:
    description: 'The path to the plugin to build'
runs:
  using: 'node12'
  main: 'dist/index.js'
