name: 'IPS Build'
description: 'Build an IPS plugin or theme into the distribution XML'
author: 'Jack Wickham'
inputs:
  type:
    description: 'The type that is being built - either plugin or theme'
    required: true
  name:
    description: 'The plugin name'
    required: true
  author:
    description: 'The plugin author'
    required: false
  website:
    description: 'The plugin website'
    required: false
  path:
    description: 'The path to the plugin to build'
  output-dir:
    description: 'The directory where the built plugin should be stored'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
